# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fluentd", path: '/Users/yuta.iwama/src/github.com/fluent/fluentd'
gem 'pry-byebug'
