apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        app.kubernetes.io/part-of: proj1
        app.kubernetes.io/name: my-prometheus
        app.example.com/stage: development
        app.example.com/region: us-east-1
        app.example.com/site: site
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: prometheus-example
        image: prom/prometheus
        ports:
          - containerPort: 9090

---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
