---
# Source: argo-cd/templates/argocd-notifications/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-controller-secret
  labels:
    helm.sh/chart: argo-cd-4.2.2
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
