workspace(name = "vega")

load("//thirdparty:dependency.bzl", "vega_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_http_archive(
    name = "spdlog",
    urls = ["https://github.com/gabime/spdlog/archive/v1.1.0.tar.gz"],
    sha256 = "3dbcbfd8c07e25f5e0d662b194d3a7772ef214358c49ada23c044c4747ce8b19",
    build_file = "thirdparty/BUILD.spdlog",
    strip_prefix = "spdlog-1.1.0",
)

vega_repository(
    name = "thirdparty",
    repos = [
        "libev",
        "nghttp2"
    ]
)
