[package]
name = "rrpc"
version = "0.1.0"
authors = ["ganmacs"]

[dependencies]
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
futures = "0.1.14"

bytes = "0.4"
serde = "1.0"
serde_derive = "1.0"

# serde_json is just for the example, not required in general
serde_json = "1.0"