source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in hagrpc.gemspec
gemspec

gem 'grpc'
gem 'serverengine'
gem 'cool.io'
