[package]
name = "mini-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
atoi = "0.3.2"
tracing = "0.1.13"
tokio = { version = "1", features = ["full"] }
