apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ganmacs/playground.git
    targetRevision: HEAD
    path: k8s/deployment1/system/argo-cd/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
