apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store-provider-aws
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ganmacs/playground.git
    targetRevision: HEAD
    path: k8s/deployment1/system/csi-secrets-store-provider-aws/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
