apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ganmacs/playground.git
    targetRevision: HEAD
    path: k8s/deployment1/system/secrets-store-csi-driver/templates
  destination:
    server: https://kubernetes.default.svc
