apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ganmacs/playground.git
    targetRevision: HEAD
    path: k8s/deployment1/tenant/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: default
