# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'griffin'
gem 'grpc_kit'
gem 'griffin-interceptors', github: 'ganmacs/griffin-interceptors', branch: 'add-worker-killer-insterceptors'
