[package]
name = "awrite"
version = "0.1.0"
authors = ["ganmacs <ganmacs@gmail.com>"]
edition = "2018"

[dependencies]

bytes = { git = "https://github.com/tokio-rs/bytes" }
byteorder = "1.0.0"
parking_lot = "0.8"
